name: 03. 🟢 app_quant

on:
  # 使用 cron 定时执行
  schedule:
    # 关于小时的参数，我想 9:30 启动的，按理说 UTC + 8 应该是 1 才对，但是实测确实 10:30 才启动，所以改为 0
    - cron: "0 0 * * 1-5"

  workflow_dispatch:
    inputs:
      MODULE:
        description: "运行模块"
        default: "monitor"
        required: false
        type: choice
        options:
          - "monitor"

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: quant
      WITH_3PARTY: false
      ARGS: >-
        --module ${{ inputs.MODULE || github.event.client_payload.MODULE || 'monitor' }}
      COMMIT_CHANGE: false
      # SIMPLE_RUN: true

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
