name: 19. 🟢 app_action_test

on:
  # 该事件可以通过 API 触发
  repository_dispatch:
    types:
      - mypy_event_type.test_app

  # 手动触发时输入参数
  workflow_dispatch:
    inputs:
      ARGS:
        description: "排班参数用逗号分隔: 0 表示休息 1 表示上班 2 表示夜班 3 表示备班"
        required: false
        type: string
        default: ""

      REF:
        description: "Python 仓库分支或标签、提交ID"
        type: choice
        required: false
        options:
          - "master"
          - "release"

      SIMPLE_RUN:
        description: "是否简单运行（不安装程序依赖和字体）"
        type: boolean
        required: false
        default: true

      ENV_PUBLISH_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,weixin,xiaohongshu）"
        required: false
        default: "douyin"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        options:
          - "now"
          - "timing"

      ENV_PUBLISH_ACCOUNT:
        type: choice
        description: "选择账号"
        required: false
        default: "large"
        options:
          - "large"
          - "middle"
          - "test"

      DEBUG:
        description: "是否开启 SSH 连接到虚拟机"
        type: boolean
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: create annotations file
        run: |
          cat << EOF > ./annotations.json
          [
            {
              "file": "path/to/file.js",
              "line": 5,
              "title": "title for my annotation",
              "message": "my message: ${{inputs.ENV_PUBLISH_PLATFORMS}}",
              "annotation_level": "failure"
            }
          ]
          EOF
          cat ./annotations.json
      - name: Annotate Test
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "lint"
          input: "./annotations.json"

  run:
    # NOTICE: 如果通过 repository_dispatch 触发工作流，需要使用 github.event.client_payload.[参数] 来传递参数
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      # 环境变量
      ENV_PUBLISH_MOD: ${{ github.event.inputs.ENV_PUBLISH_MOD }}
      ENV_PUBLISH_PLATFORMS: ${{ github.event.inputs.ENV_PUBLISH_PLATFORMS }}
      ENV_PUBLISH_ACCOUNT: ${{ github.event.inputs.ENV_PUBLISH_ACCOUNT }}

      APP: test_app
      ARGS: ${{ inputs.ARGS || github.event.client_payload.ARGS }}
      REF: ${{ inputs.REF }}
      # SIMPLE_RUN: ${{ inputs.SIMPLE_RUN || github.event.client_payload.SIMPLE_RUN }}
      # COMMIT_CHANGE: ${{ inputs.COMMIT_CHANGE || github.event.client_payload.COMMIT_CHANGE || false }}
      COMMIT_CHANGE: false
      DEBUG: ${{ inputs.DEBUG || false }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
