name: Clone Public Repo

on:
  push:
    branches:
      - main

jobs:
  clone_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: M-Kepler/Python.git
          token: ${{ secrets.MYPY_ACCESS_TOKEN }}
