name: 🍎 app_y2dy

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: "-m once 表示运行一次; -m loop 表示持续监控"
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-m loop"

  # 定时执行
  schedule:
    # 代表国际标准时间，实际北京时间需要 +8 小时
    - cron: "30 14 * * *"

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: youtu2douyin
      # 定时执行没传这个值也可以，在 run.yml 已经做了处理了
      ARGS: ${{ inputs.ARGS }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
